name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Compile with Makefile
      run: make
      
#    - name: Run tests
#      run: ./minishell --test  # Suponiendo que tienes pruebas automatizadas
    
    - name: Display success message
      run: echo "El programa compilado exitosamente."
