name: Build the minishell C project

on:
  push:
    branches: [ "carlos" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Build project
      run: make
    
   # - name: run minishell
    #  run: ./minishell
 #   - name: Commit and pushchanges
#      uses: stefanzweifel/git-auto-commit-action@v5
